### ISSUE TITLE
Problem in maximization

### ISSUE THREAD

**Issue by adhe-k** [industrial-optimization-group/desdeo-emo#13]
An error occurred when I used maximization :
f1 = _ScalarObjective(name='f1', evaluator=f_1, maximize=True)

This is the error : 
  File "/home/ai/anaconda3/lib/python3.7/site-packages/desdeo_problem/Problem.py", line 718, in __init__
    to_maximize = sum(to_maximize, [])  # To flatten the list
TypeError: can only concatenate list (not "bool") to list

**Comment by light-weaver** [comment]
Fixed.
